 CREATE OR REPLACE  PROCEDURE insert_ANSWER
/*AUTHID CURRENT_USER*/
IS
BEGIN
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (1,1,1,''текст'',''const'',''Стоимость работ от '',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (1,1,2,''текст'',''текст'','''',NULL,NULL,''девятисот пятидесяти'',20,67)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (1,1,3,''текст'',''const'','' рублей.'',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (1,2,1,''текст'',''const'',''Достаточно '',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (1,2,2,''текст'',''текст'','''',NULL,NULL,''четырёхсот шестидесяти восьми'',29,67)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (1,2,3,''текст'',''const'','' мониторов.'',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (1,3,1,''текст'',''const'',''Обратиться к '',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (1,3,2,''текст'',''текст'','''',NULL,NULL,''восьмистам девяноста двум'',25,68)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (1,3,3,''текст'',''const'','' слушателям.'',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (1,4,1,''текст'',''const'',''Офис находится в '',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (1,4,2,''текст'',''текст'','''',NULL,NULL,''полутора'',8,70)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (1,4,3,''текст'',''const'','' километрах от вокзала.'',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (3,23,1,''текст'',''текст'','''',NULL,NULL,''Алексею Седых'',13,78)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (3,21,1,''текст'',''текст'','''',NULL,NULL,''Юрию Живаго'',11,156)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (3,22,1,''текст'',''текст'','''',NULL,NULL,''Евгению Гранде'',14,157)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (3,28,1,''текст'',''текст'','''',NULL,NULL,''Ирине Романович'',15,159)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (3,29,1,''текст'',''текст'','''',NULL,NULL,''Владимиру Сидоровичу'',20,158)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (3,27,1,''текст'',''текст'','''',NULL,NULL,''Зурабу Соткилаве'',16,69)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (3,30,1,''текст'',''текст'','''',NULL,NULL,''Олегу Езусу'',11,158)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (3,31,1,''текст'',''текст'','''',NULL,NULL,''Сергею Хмилю'',12,160)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (3,24,1,''текст'',''текст'','''',NULL,NULL,''Светлане Гусь'',13,79)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (3,25,1,''текст'',''текст'','''',NULL,NULL,''Анне Фрейд'',10,80)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (3,26,1,''текст'',''текст'','''',NULL,NULL,''Елене Мотыль'',12,79)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (3,32,1,''текст'',''текст'','''',NULL,NULL,''Владимиру Галаху'',16,161)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (3,33,1,''текст'',''текст'','''',NULL,NULL,''Наталье Бибик'',13,159)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (3,34,1,''текст'',''текст'','''',NULL,NULL,''Сергею Пашуку'',13,161)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (3,35,1,''текст'',''текст'','''',NULL,NULL,''Александру Панюте'',17,69)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (6,36,1,''символ'',''const'',''Мы сегодня занимались монтаж'',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (6,36,2,''символ'',''буква'','''',NULL,NULL,''о'',1,82)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (6,36,3,''символ'',''const'',''м видеоролика, который будет уча'',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (6,36,4,''символ'',''буква'','''',NULL,NULL,''ст'',2,162)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (6,36,5,''символ'',''const'',''вовать в конкурсе «Мы-команда».'',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (6,37,1,''символ'',''const'',''В нашем управлении работают два молодых стаж'',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (6,37,2,''символ'',''буква'','''',NULL,NULL,''ё'',1,83)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (6,37,3,''символ'',''const'',''ра.'',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (6,38,1,''символ'',''const'',''Н'',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (6,38,2,''символ'',''буква'','''',NULL,NULL,''и'',1,163)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (6,38,3,''символ'',''const'',''когда не доводилось нам видеть н'',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (6,38,4,''символ'',''буква'','''',NULL,NULL,''и'',1,163)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (6,38,5,''символ'',''const'',''чего более удивительного.'',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (7,58,1,''символ'',''const'',''Я старался '',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (7,58,2,''символ'',''список'','''',4,10,''никого '',6,172)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (7,58,3,''символ'',''список'','''',15,53,''не вводить'',10,123)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (7,58,4,''символ'',''const'','' в заблуждение, '',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (7,58,5,''символ'',''список'','''',16,55,''не использовать'',15,123)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (7,58,6,''символ'',''список'','''',17,57,''непроверенные'',13,173)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (7,58,7,''символ'',''const'','' факты и домыслы.'',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (7,51,1,''символ'',''список'','''',97,244,''Нелёгкое'',8,88)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (7,51,2,''символ'',''const'','' задание.'',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (7,52,1,''символ'',''список'','''',98,248,''Не раскрытая'',12,89)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (7,52,2,''символ'',''const'','' мной книга'',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (7,53,1,''символ'',''const'',''После '',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (7,53,2,''символ'',''список'','''',99,254,''непродолжительного'',18,88)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (7,53,3,''символ'',''const'','' перерыва в работе конференции все '',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (7,53,4,''символ'',''список'','''',100,257,''участники'',9,162)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (7,53,5,''символ'',''const'','' принялись '',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (7,53,6,''символ'',''список'','''',101,259,''снова'',5,171)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (7,53,7,''символ'',''const'','' за работу.'',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (7,54,1,''символ'',''список'','''',102,262,''Ввиду'',5,115)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (7,54,2,''символ'',''const'','' недостатка времени совещание перенесено на завтра.'',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (7,55,1,''символ'',''const'',''В его словах нет '',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (7,55,2,''символ'',''список'','''',7,21,''ничего'',6,124)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (7,55,3,''символ'',''const'','', '',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (7,55,4,''символ'',''список'','''',103,265,''что бы'',6,17)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (7,55,5,''символ'',''const'','' заставило меня изменить принятое решение.'',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (7,56,1,''символ'',''const'',''В нашей службе работают '',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (7,56,2,''символ'',''список'','''',104,268,''высококвалифицированные'',23,46)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (7,56,3,''символ'',''const'','' специалисты.'',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (7,65,1,''символ'',''список'','''',117,302,''Законный'',8,129)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (7,65,2,''символ'',''const'','' владелец банковской карты предъявил претензии отделению о '',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (7,65,3,''символ'',''список'','''',118,306,''необоснованном'',14,130)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (7,65,4,''символ'',''const'','' взимании '',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (7,65,5,''символ'',''список'','''',119,309,''комиссионного'',13,176)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (7,65,6,''символ'',''const'','' вознаграждения.'',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (7,59,1,''символ'',''const'',''Праздник, '',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (7,59,2,''символ'',''список'','''',105,271,''организованный'',14,130)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (7,59,3,''символ'',''const'','' в 2018 году, в честь образования нашей Службы, стал '',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (7,59,4,''символ'',''список'','''',106,273,''традиционным'',12,48)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (7,59,5,''символ'',''const'',''.'',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (7,60,1,''символ'',''const'',''Время выполнения вкладных операций, '',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (7,60,2,''символ'',''список'','''',107,274,''предусмотренное'',15,137)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (7,60,3,''символ'',''const'','' в системе управления очередью, '',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (7,60,4,''символ'',''список'','''',108,277,''ограничено'',10,99)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (7,60,5,''символ'',''const'','' для каждого вида.'',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (7,61,1,''символ'',''const'',''По итогам квартала, в качестве '',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (7,61,2,''символ'',''список'','''',120,313,''мотивационной'',13,129)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (7,61,3,''символ'',''const'','' составляющей, всем результативным сотрудникам '',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (7,61,4,''символ'',''список'','''',109,278,''выставлены'',10,174)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (7,61,5,''символ'',''const'','' '',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (7,61,6,''символ'',''список'','''',116,301,''повышенные'',10,137)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (7,61,7,''символ'',''const'','' оценки по Системе 5+ .'',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (7,62,1,''символ'',''const'',''Документ нужен в '',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (7,62,2,''символ'',''список'','''',110,280,''распечатанном'',13,39)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (7,62,3,''символ'',''const'','' или '',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (7,62,4,''символ'',''список'','''',111,282,''электронном'',11,48)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (7,62,5,''символ'',''const'','' виде?'',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (6,39,1,''символ'',''const'',''Однажды Гейтс объявил о том, что готов соед'',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (6,39,2,''символ'',''буква'','''',NULL,NULL,''и'',1,100)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (6,39,3,''символ'',''const'',''нить все библиотеки Америки с помощью сети Интернет.'',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (6,40,1,''символ'',''const'',''Сегодня мы че'',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (6,40,2,''символ'',''буква'','''',NULL,NULL,''ст'',2,103)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (6,40,3,''символ'',''const'',''вовали наших победителей конкурса.'',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (6,41,1,''символ'',''const'',''Попробуем порассуждать о проблемах создания и'',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (6,41,2,''символ'',''буква'','''',NULL,NULL,''с'',1,104)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (6,41,3,''символ'',''const'',''ку'',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (6,41,4,''символ'',''буква'','''',NULL,NULL,''сс'',2,104)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (6,41,5,''символ'',''const'',''тве'',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (6,41,6,''символ'',''буква'','''',NULL,NULL,''нн'',2,48)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (6,41,7,''символ'',''const'',''ого инт'',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (6,41,8,''символ'',''буква'','''',NULL,NULL,''елл'',3,164)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (6,41,9,''символ'',''const'',''екта, его влиянии на человека и общество.'',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (7,63,1,''символ'',''const'',''Дисциплинарное взыскание к сотруднику '',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (7,63,2,''символ'',''список'','''',112,284,''не применено'',12,41)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (7,63,3,''символ'',''const'',''  -  '',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (7,63,4,''символ'',''список'','''',113,288,''недостаточно'',12,175)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (7,63,5,''символ'',''const'',''  доказательств.'',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,66,1,''символ'',''const'',''Проверяющие начали согласовывать проекты актов'',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,66,2,''символ'',''знак'','''',NULL,NULL,'','',1,106)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,66,3,''символ'',''const'','' и руководитель проверк'',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,66,4,''символ'',''буква'','''',NULL,NULL,''и'',1,178)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,66,5,''символ'',''знак'','''',NULL,NULL,''пусто'',1,183)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,66,6,''символ'',''const'','' всем напомнил'',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,66,7,''символ'',''знак'','''',NULL,NULL,''пусто'',1,183)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,66,8,''символ'',''const'','' о том'',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,66,9,''символ'',''знак'','''',NULL,NULL,'','',1,54)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,66,10,''символ'',''const'','' что подписать материал'',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,66,11,''символ'',''знак'','''',NULL,NULL,''пусто'',1,183)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,66,12,''символ'',''const'','' нужно в четверг.'',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,80,1,''символ'',''const'',''К'',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,80,2,''символ'',''список'','''',82,213,''о'',1,16)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,80,3,''символ'',''const'',''мпания'',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,67,1,''символ'',''const'',''Все игроки получат удовольстви'',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,67,2,''символ'',''буква'','''',NULL,NULL,''е'',1,180)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,67,3,''символ'',''const'','' от процесса'',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,67,4,''символ'',''знак'','''',NULL,NULL,'':'',1,131)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,67,5,''символ'',''const'','' организаторы расскажут много нового'',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,67,6,''символ'',''знак'','''',NULL,NULL,''пусто'',1,183)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,67,7,''символ'',''const'','' и интере'',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,67,8,''символ'',''буква'','''',NULL,NULL,''сн'',2,181)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,67,9,''символ'',''const'',''ого'',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,67,10,''символ'',''знак'','''',NULL,NULL,'','',1,9)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,67,11,''символ'',''const'','' вспомнят хорошо забытое старое'',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,67,12,''символ'',''знак'','''',NULL,NULL,''пусто'',1,183)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,67,13,''символ'',''const'','' и прокачают стратегическое мышление.'',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (7,64,1,''символ'',''const'',''Если работник вносит '',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (7,64,2,''символ'',''список'','''',114,294,''корректировку'',13,164)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (7,64,3,''символ'',''const'',''  во '',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (7,64,4,''символ'',''список'','''',115,297,''внесенные'',9,137)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (7,64,5,''символ'',''const'','' ранее документы, система уведомляет об этом руководителя.'',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,76,1,''символ'',''const'',''Законы'',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,76,2,''символ'',''знак'','''',NULL,NULL,'','',1,52)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,76,3,''символ'',''const'','' на которые мы опираемся'',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,76,4,''символ'',''знак'','''',NULL,NULL,'',-'',2,112)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,76,5,''символ'',''const'',''это нормативные акты государства'',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,76,6,''символ'',''знак'','''',NULL,NULL,'','',1,145)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,76,7,''символ'',''const'',''подлежащие неукоснительному исполнению.'',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,77,1,''символ'',''const'',''Разработка нормативных значений об'',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,77,2,''символ'',''буква'','''',NULL,NULL,''о'',1,188)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,77,3,''символ'',''const'',''рачиваемости запасов '',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,77,4,''символ'',''знак'','''',NULL,NULL,''-'',1,189)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,77,5,''символ'',''const'',''новое задание руководства.'',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,78,1,''символ'',''const'',''Согласно дорожной карт'',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,78,2,''символ'',''буква'','''',NULL,NULL,''е'',1,4)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,78,3,''символ'',''знак'','''',NULL,NULL,'','',1,107)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,78,4,''символ'',''const'','' утвержденной руководством Банка'',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,78,5,''символ'',''знак'','''',NULL,NULL,'','',1,107)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,78,6,''символ'',''const'','' ответственность за ид'',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,78,7,''символ'',''знак'','''',NULL,NULL,''е'',1,164)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,78,8,''символ'',''const'',''нтификацию имущества '',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,78,9,''символ'',''знак'','''',NULL,NULL,'','',1,9)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,78,10,''символ'',''const'',''высвобождение помещений'',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,78,11,''символ'',''знак'','''',NULL,NULL,'','',1,37)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,78,12,''символ'',''const'',''  в т.ч. проведение коммуникаций и проведение переговоров с интересантами '',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,78,15,''символ'',''знак'','''',NULL,NULL,'','',1,37)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,78,16,''символ'',''const'',''возложена на управляющего отделением.'',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,68,1,''символ'',''const'',''Как только появится возможность опред'',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,68,2,''символ'',''список'','''',76,199,''е'',1,50)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,68,3,''символ'',''const'',''лить'',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,68,4,''символ'',''знак'','''',NULL,NULL,'','',1,138)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,68,5,''символ'',''const'','' что на самом деле'',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,68,6,''символ'',''знак'','''',NULL,NULL,''пусто'',1,183)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,68,7,''символ'',''const'','' мы хотим получить в итоге'',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,68,8,''символ'',''знак'','''',NULL,NULL,'','',1,200)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,68,9,''символ'',''const'','' все действия подстроятся под достижение этой цели. Если заметите'',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,68,10,''символ'',''знак'','''',NULL,NULL,'','',1,5)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,68,11,''символ'',''const'','' что решения отклоняются от главной цели'',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,68,12,''символ'',''знак'','''',NULL,NULL,'',-'',2,139)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,68,13,''символ'',''const'','' это знак'',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,68,14,''символ'',''знак'','''',NULL,NULL,'','',1,54)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,68,15,''символ'',''const'','' что нужно сменить курс.'',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,79,1,''символ'',''const'',''Установить'',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,79,2,''символ'',''знак'','''',NULL,NULL,''пусто'',1,183)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,79,3,''символ'',''const'','' фактическое местонахождение автотранспорта'',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,79,4,''символ'',''знак'','''',NULL,NULL,''пусто'',1,183)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,79,5,''символ'',''const'','' должника'',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,79,6,''символ'',''знак'','''',NULL,NULL,'','',1,143)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,79,7,''символ'',''const'',''переда'',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,79,8,''символ'',''буква'','''',NULL,NULL,''нн'',2,39)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,79,9,''символ'',''const'',''ого в залог'',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,79,10,''символ'',''знак'','''',NULL,NULL,'','',1,143)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,79,11,''символ'',''const'','' не удалось'',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,79,12,''символ'',''знак'','''',NULL,NULL,''-'',1,10)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,79,13,''символ'',''const'','' продано'',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,79,14,''символ'',''знак'','''',NULL,NULL,''пусто'',1,183)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,79,15,''символ'',''const'','' третьим лицам.'',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,69,1,''символ'',''const'',''Выдан кредит'',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,69,2,''символ'',''знак'','''',NULL,NULL,''пусто'',1,183)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,69,3,''символ'',''const'','' при н'',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,69,4,''символ'',''буква'','''',NULL,NULL,''е'',1,86)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,69,5,''символ'',''const'',''выполненном отлагательном условии'',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,69,6,''символ'',''знак'','''',NULL,NULL,'','',1,52)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,69,7,''символ'',''const'','' которое заключалось в н'',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,69,8,''символ'',''буква'','''',NULL,NULL,''е'',1,88)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,69,9,''символ'',''const'',''соблюдении графика'',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,69,10,''символ'',''знак'','''',NULL,NULL,''пусто'',1,183)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,73,7,''символ'',''const'','' неизве'',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,73,8,''символ'',''буква'','''',NULL,NULL,''ст'',2,187)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (7,57,1,''символ'',''const'',''Данная опция осуществляет поиск '',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (7,57,2,''символ'',''список'','''',87,224,''немаскированных'',15,24)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (7,57,3,''символ'',''const'','' данных и подсвечивает красным цветом текст тех предложений/словосочетаний, в которых данные '',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (7,57,4,''символ'',''список'','''',88,226,''не маскированы'',14,25)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (7,57,5,''символ'',''const'',''.'',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,71,1,''символ'',''const'',''Согласно нормативны'',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,71,2,''символ'',''список'','''',89,228,''м'',1,27)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,71,3,''символ'',''const'','' документ'',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,71,4,''символ'',''список'','''',90,230,''ам'',2,27)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,71,5,''символ'',''знак'','''',NULL,NULL,''пусто'',1,184)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,71,6,''символ'',''const'','' для подтверждения'',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,71,7,''символ'',''знак'','''',NULL,NULL,''пусто'',1,183)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,71,8,''символ'',''const'','' и согласования стоимости поездки'',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,71,9,''символ'',''знак'','''',NULL,NULL,'','',1,36)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,71,10,''символ'',''const'','' в карточку добавляют фотоснимок билета'',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,71,11,''символ'',''знак'','''',NULL,NULL,''пусто'',1,183)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,71,12,''символ'',''const'','' или снимок с информацией'',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,71,13,''символ'',''знак'','''',NULL,NULL,'','',1,36)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,71,14,''символ'',''const'','' в том числе получе'',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,71,15,''символ'',''список'','''',37,106,''нн'',2,39)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,71,16,''символ'',''const'',''ой из открытых источников'',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,71,17,''символ'',''знак'','''',NULL,NULL,'','',1,36)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,71,18,''символ'',''const'','' подтверждающей стоимость данной поездки.'',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,72,1,''символ'',''const'',''Работники Банка'',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,72,2,''символ'',''знак'','''',NULL,NULL,'','',1,145)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,72,3,''символ'',''const'','' использующие транспорт'',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,72,4,''символ'',''знак'','''',NULL,NULL,'','',1,145)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,72,5,''символ'',''const'','' при заполнени'',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,72,6,''символ'',''буква'','''',NULL,NULL,''и'',1,185)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,72,7,''символ'',''const'',''  на портале обращения для согласования'',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,72,8,''символ'',''знак'','''',NULL,NULL,''пусто'',1,183)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,72,9,''символ'',''const'','' добавляют фотоснимок проездного документа'',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,72,10,''символ'',''знак'','''',NULL,NULL,''пусто'',1,183)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,72,11,''символ'',''const'','' и снимок с информацией'',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,72,12,''символ'',''знак'','''',NULL,NULL,'','',1,30)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,72,13,''символ'',''const'','' в том числе получе'',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,72,14,''символ'',''список'','''',37,106,''нн'',2,39)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,72,15,''символ'',''const'',''ой из открытых источников'',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,72,16,''символ'',''знак'','''',NULL,NULL,'','',1,30)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,72,17,''символ'',''const'','' по'',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,72,18,''символ'',''буква'','''',NULL,NULL,''д'',1,186)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,72,19,''символ'',''const'',''тверждающей стоимость поездки.'',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (1,5,1,''текст'',''const'',''Оформили '',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (1,5,2,''текст'',''текст'','''',NULL,NULL,''триста'',6,148)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (1,5,3,''текст'',''const'','' документов.'',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (1,6,1,''текст'',''const'',''Заключили '',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (1,6,2,''текст'',''текст'','''',NULL,NULL,''четыреста'',9,148)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (1,6,3,''текст'',''const'','' договоров.'',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (1,7,1,''текст'',''const'',''Сообщения были направлены '',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (1,7,2,''текст'',''текст'','''',NULL,NULL,''двумстам'',8,149)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (1,7,3,''текст'',''const'','' сотрудникам.'',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (1,8,1,''текст'',''const'',''Обучение необходимо пройти ещё '',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (1,8,2,''текст'',''текст'','''',NULL,NULL,''трёмстам'',8,150)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (1,8,3,''текст'',''const'','' сотрудникам.'',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (1,9,1,''текст'',''const'',''Премиальный фонд распределили между '',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (1,9,2,''текст'',''текст'','''',NULL,NULL,''четырьмястами'',13,151)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (1,9,3,''текст'',''const'','' сотрудниками.'',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (1,10,1,''текст'',''const'',''Грамоты вручили '',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (1,10,2,''текст'',''текст'','''',NULL,NULL,''семистам'',8,152)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (1,10,3,''текст'',''const'','' участникам.'',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (41,11,1,''текст'',''текст'','''',NULL,NULL,''Восьмимиллионный'',15,153)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (41,11,2,''текст'',''const'','' доход.'',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (41,12,1,''текст'',''текст'','''',NULL,NULL,''Семимиллиардный'',15,153)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (41,12,2,''текст'',''const'','' капитал.'',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (41,13,1,''текст'',''текст'','''',NULL,NULL,''Стотысячный'',11,153)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (41,13,2,''текст'',''const'','' клиент.'',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (41,14,1,''текст'',''текст'','''',NULL,NULL,''Стотридцатимиллионный'',21,153)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (41,14,2,''текст'',''const'','' оборот.'',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (41,15,1,''текст'',''текст'','''',NULL,NULL,''Двухсотмиллионное'',17,153)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (41,15,2,''текст'',''const'','' население.'',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (41,16,1,''текст'',''текст'','''',NULL,NULL,''Двадцатипятилетний'',18,154)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (41,16,2,''текст'',''const'','' юбилей.'',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (41,17,1,''текст'',''текст'','''',NULL,NULL,''Пятилетний'',10,154)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (41,17,2,''текст'',''const'','' опыт.'',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (41,18,1,''текст'',''текст'','''',NULL,NULL,''Десятирублёвый'',14,154)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (41,18,2,''текст'',''const'','' билет.'',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (41,19,1,''текст'',''текст'','''',NULL,NULL,''Шестиметровая'',13,154)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (41,19,2,''символ'',''const'','' дистанция.'',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (41,20,1,''текст'',''текст'','''',NULL,NULL,''Двести тридцать пять'',20,155)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (41,20,2,''текст'',''const'','' кабинетов.'',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (6,43,1,''символ'',''const'',''Пр'',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (6,43,2,''символ'',''буква'','''',NULL,NULL,''е'',1,165)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (6,43,3,''символ'',''const'',''бывание в командировке пр'',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (6,43,4,''символ'',''буква'','''',NULL,NULL,''и'',1,166)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (6,43,5,''символ'',''const'',''несло большую пользу.'',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (6,44,1,''символ'',''const'',''Слушатели пр'',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (6,44,2,''символ'',''буква'','''',NULL,NULL,''и'',1,156)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (6,44,3,''символ'',''const'',''соединились к мнению докладчика.'',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (6,45,1,''символ'',''const'',''Необходимо кратко изл'',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (6,45,2,''символ'',''буква'','''',NULL,NULL,''о'',1,167)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (6,45,3,''символ'',''const'',''жить содержание статьи.'',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (6,46,1,''символ'',''const'',''Надо подготови'',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (6,46,2,''символ'',''буква'','''',NULL,NULL,''ть'',2,168)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (6,46,3,''символ'',''const'',''ся к проверке.'',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (6,47,1,''символ'',''const'',''Наш коллектив горди'',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (6,47,2,''символ'',''буква'','''',NULL,NULL,''т'',1,168)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (6,47,3,''символ'',''const'',''ся своими достижениями.'',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (6,48,1,''символ'',''const'',''Интересной книгой нельзя не увле'',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (6,48,2,''символ'',''буква'','''',NULL,NULL,''чь'',2,168)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (6,48,3,''символ'',''const'',''ся.'',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (6,49,1,''символ'',''const'',''Пора соб'',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (6,49,2,''символ'',''буква'','''',NULL,NULL,''и'',1,169)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (6,49,3,''символ'',''const'',''ра'',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (6,49,4,''символ'',''буква'','''',NULL,NULL,''ть'',2,168)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (6,49,5,''символ'',''const'',''ся в ком'',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (6,49,6,''символ'',''буква'','''',NULL,NULL,''а'',1,164)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (6,49,7,''символ'',''const'',''ндировку.'',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (6,50,1,''символ'',''const'',''Всех ур'',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (6,50,2,''символ'',''буква'','''',NULL,NULL,''а'',1,170)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (6,50,3,''символ'',''const'',''вняли в правах.'',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,70,1,''символ'',''const'',''Документы некатег'',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,70,2,''символ'',''буква'','''',NULL,NULL,''о'',1,50)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,70,3,''символ'',''const'',''рирова'',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,70,4,''символ'',''буква'','''',NULL,NULL,''н'',1,99)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,70,5,''символ'',''const'',''ы'',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,70,6,''символ'',''знак'','''',NULL,NULL,'','',1,182)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,70,7,''символ'',''const'','' но содержат критичную информацию'',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,70,8,''символ'',''знак'','''',NULL,NULL,'':'',1,141)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,70,9,''символ'',''const'','' данные платёжных карт'',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,70,10,''символ'',''знак'','''',NULL,NULL,'','',1,9)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,70,11,''символ'',''const'','' персональные данные клиентов'',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,73,1,''символ'',''const'',''Централизова'',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,73,2,''символ'',''буква'','''',NULL,NULL,''нн'',2,130)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,73,3,''символ'',''const'',''ое поручение было выполнено'',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,73,4,''символ'',''знак'','''',NULL,NULL,'','',1,182)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,73,5,''символ'',''const'','' но'',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,73,6,''символ'',''знак'','''',NULL,NULL,''пусто'',1,183)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,73,9,''символ'',''const'',''но кем'',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,73,10,''символ'',''знак'','''',NULL,NULL,'','',1,58)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,73,11,''символ'',''const'','' так как исполнитель не проставил свою фамилию.'',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,74,1,''символ'',''const'',''На конференции не только обсуждали персп'',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,74,2,''символ'',''буква'','''',NULL,NULL,''е'',1,101)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,74,3,''символ'',''const'',''ктивы сотрудничества по совме'',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,74,4,''символ'',''буква'','''',NULL,NULL,''ст'',2,103)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,74,5,''символ'',''const'',''ным проектам'',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,74,6,''символ'',''знак'','''',NULL,NULL,'','',1,182)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,74,7,''символ'',''const'','' но '',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,74,8,''символ'',''знак'','''',NULL,NULL,''пусто'',1,183)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,74,9,''символ'',''const'',''и были составлены дорожные карты'',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,74,10,''символ'',''знак'','''',NULL,NULL,'','',1,40)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,74,11,''символ'',''const'','' и подписаны соглашения'',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,74,12,''символ'',''знак'','''',NULL,NULL,'','',1,40)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,75,1,''символ'',''const'',''Следует отметить'',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,75,2,''символ'',''знак'','''',NULL,NULL,'','',1,32)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,75,3,''символ'',''const'','' что '',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,75,4,''символ'',''знак'','''',NULL,NULL,''пусто'',1,183)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,75,5,''символ'',''const'',''неко'',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,75,6,''символ'',''буква'','''',NULL,NULL,''рр'',2,164)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,75,7,''символ'',''const'',''ектно установленные показатели об'',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,75,8,''символ'',''буква'','''',NULL,NULL,''о'',1,188)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,75,9,''символ'',''const'',''рачиваемости и'',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,75,10,''символ'',''буква'','''',NULL,NULL,''с'',1,104)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,75,11,''символ'',''const'',''ку'',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,75,12,''символ'',''буква'','''',NULL,NULL,''сс'',2,104)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,75,13,''символ'',''const'',''твенно улучшают показатели чистого денежного потока.'',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,70,12,''символ'',''знак'','''',NULL,NULL,''пусто'',1,183)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,70,13,''символ'',''const'','' и сотрудников Банка'',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,70,14,''символ'',''знак'','''',NULL,NULL,'','',1,9)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,70,15,''символ'',''const'','' счета клиентов.'',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,69,11,''символ'',''const'','' строительства об'',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,69,12,''символ'',''буква'','''',NULL,NULL,''ъ'',1,202)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,69,13,''символ'',''const'',''екта.'',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,80,4,''символ'',''знак'','''',NULL,NULL,''пусто'',1,183)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,80,5,''символ'',''const'','' нанимает аген'',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,80,6,''символ'',''буква'','''',NULL,NULL,''тст'',3,205)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,80,7,''символ'',''const'',''ва'',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,80,8,''символ'',''знак'','''',NULL,NULL,'','',1,143)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,80,9,''символ'',''const'','' занимающиеся организацией рекламных к'',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,80,10,''символ'',''список'','''',82,212,''а'',1,16)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,80,11,''символ'',''const'',''мпаний'',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,80,12,''символ'',''знак'','''',NULL,NULL,'','',1,143)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,80,13,''символ'',''const'','' для продвижения'',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,80,14,''символ'',''знак'','''',NULL,NULL,''пусто'',1,183)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,80,15,''символ'',''const'','' своих новых продуктов.'',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,74,13,''символ'',''const'','' и ра'',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,74,14,''символ'',''буква'','''',NULL,NULL,''сс'',2,204)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,74,15,''символ'',''const'',''тавлены пр'',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,74,16,''символ'',''буква'','''',NULL,NULL,''и'',1,164)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (40,74,17,''символ'',''const'',''оритеты.'',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (7,42,1,''символ'',''const'',''Сотрудника расспрашивали о событиях, которые '',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (7,42,2,''символ'',''список'','''',121,317,''не могли'',8,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (7,42,3,''символ'',''const'','' иметь '',NULL,NULL,'''',NULL,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (7,42,4,''символ'',''список'','''',9,29,''никакого'',8,NULL)';
  EXECUTE IMMEDIATE 'INSERT INTO ANSWER VALUES (7,42,5,''символ'',''const'','' отношения к предмету проводимого расследования.'',NULL,NULL,'''',NULL,NULL)';

END insert_ANSWER;
